# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/raven/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),raven)

$(call add-radio-file-sha1-checked,radio/abl.img,e3100c050bd7ef84356c23af6d332c61c7f8180c)
$(call add-radio-file-sha1-checked,radio/bl1.img,61e543927f8b72fb258dcde49d2a8615d8df392c)
$(call add-radio-file-sha1-checked,radio/bl2.img,b3d4cee6549c5a4eb25e55de161bdeae8b21845e)
$(call add-radio-file-sha1-checked,radio/bl31.img,5996224bc2889e0b4f0491e750d9f53f18c94ec2)
$(call add-radio-file-sha1-checked,radio/gsa.img,e904f23c86e935e6f3e7b507df65f5792d1569a5)
$(call add-radio-file-sha1-checked,radio/ldfw.img,ded5a7b0315622a523952f8644ea9c79e88e75a1)
$(call add-radio-file-sha1-checked,radio/modem.img,79b2066cd4dfe9fe404dc5865db3bd9e6cf155f2)
$(call add-radio-file-sha1-checked,radio/pbl.img,6f867a101d9777d95f9032d6949f39869870c4ea)
$(call add-radio-file-sha1-checked,radio/tzsw.img,15b4ba2e980bdcb4f3705bdc86ccd39d1693222f)

endif
